name = "bf"
version = "0.1.0"
license = "MIT"
author = "SRAZKVT"
maintainer = "sarah.mathey66666@gmail.com"
copyright = "Copyright 2022, SRAZKVT"
[build]
auto-executables = true
[install]
library = false
